name: Daily Auto Check-In

on:
  schedule:
    - cron: '0 2 * * *' # mỗi ngày lúc 09:00 sáng VN (GMT+7)
  workflow_dispatch: # cho phép chạy thủ công

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Check-In
        env:
          TOKEN_1: ${{ secrets.TOKEN_1 }}
          TOKEN_2: ${{ secrets.TOKEN_2 }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: node scripts/checkin.cjs # build sẵn nếu dùng TypeScript
